---
- name: Install node and npm
  hosts: ec2
  become: yes
  become_user: root
  tasks:
    - name: Update package cache
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Node.js prerequisites
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: gcc-c++,make

    - name: Install Node.js
      shell: | 
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        . ~/.nvm/nvm.sh
        nvm install 16

- name: Create new linux user for node app
  hosts: ec2
  become: yes   
  vars_files:
    - vars-projects  
  tasks:
    - name: Create linux user
      ansible.builtin.user:
        name: "{{linux_name}}"
        comment: Node User
        groups: adm


- name: Deploy nodejs app
  hosts: ec2
  become: True
  become_user: "{{linux_name}}"
  vars_files:
    - vars-projects
  tasks:
    - name: Unpack the nodejs file
      ansible.builtin.unarchive:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{user_home_dir}}"
    - name: Install dependencies
      community.general.npm:
        path: "{{user_home_dir}}/package"
    - name: Start the application
      ansible.builtin.command: 
        chdir: "{{user_home_dir}}/package/app"
        cmd: node server
      async: 1000
      poll: 0  
    - name: Ensure app is running
      ansible.builtin.shell: ps aux | grep node
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
