# Install Pyhon3. docker, docker-compose on Amazon Linux 2. Add user in groups: adm. Start docker. Pull docker image from private repo. Start game2048
---
- name: Wait for ssh connection # add timing issue
  host: all
  gather_facts: False
  tasks: 
    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 10 # 10 sec
        timout: 100
        host: '{{ (ansible_ssh_host|defoult(ansible_host))|defoult(inventory_hostname) }}'
      vars:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python


- name: Install python3, docker, docker-compose
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      ansible.builtin.get_url: 
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Install docker python module
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose
          - urllib3==1.26.15
    

- name: Add ec2-user to docker group
  hosts: all
  become: yes
  tasks: 
    - name: Add ec2-user to docker group
      ansible.builtin.user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      ansible.builtin.meta: reset_connection


- name: Start docker containers
  hosts: all
  vars_files:
    - vars-projects
  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: "{{location}}/docker-compose-full.yaml"
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      community.docker.docker_login: 
        registry_url: https://index.docker.io/v1/
        username: voiz80
        password: "{{docker_password}}"
    - name: Start container from compose
      community.docker.docker_compose: 
        project_src: /home/ec2-user
        state: present # docker-compose up | "absent" - docker-compose down 
